export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST';
export const REMOVE_SONG_FROM_PLAYLIST = 'REMOVE_SONG_FROM_PLAYLIST';
export const SONGS_FETCH_DATA_SUCCESS = 'SONGS_FETCH_DATA_SUCCESS';
export const SET_SONG_PLAYING_ID = 'SET_SONG_PLAYING_ID';
export const SET_PLAYLIST_SONG_PLAYING_INDEX = 'SET_PLAYLIST_SONG_PLAYING_INDEX';
export const SET_PLAYLIST = 'SET_PLAYLIST';
